import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { api, setCsrf, Project, ProjectSummary, Run } from './api';
import { ConversationPanel, ArtifactTabs, PrototypeCanvas } from './workbench';
import { ModelSettings } from './model-settings';
import { SourcePanel, VersionHistory, ConfirmationPanel, DocumentStudio } from './panels';
import { AppShell, ProjectSwitcher, useDialog } from './shell';
import './style.css';

type Obj = Record<string, any>;
const statusNames: Obj = { queued: '排队', running: '运行中', succeeded: '已执行', partial: '部分完成', awaiting_user: '等待回答', failed: '失败', paused_budget: '预算暂停', cancelled: '已取消', read: '已读取', awaiting_vision: '待视觉分析', candidate: '候选', selected: '本期已选', rejected: '未采纳', deferred: '暂缓', open: '待回答', answered: '已回答' };
function App() {
  const [logged, setLogged] = useState(false), [token, setToken] = useState(''), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  const [projects, setProjects] = useState<ProjectSummary[]>([]), [p, setP] = useState<Project | null>(null), [tab, setTab] = useState('conversation');
  const [models, setModels] = useState<Obj>({}), [runs, setRuns] = useState<Run[]>([]), [message, setMessage] = useState(''), [stage, setStage] = useState('ingest'), [docType, setDocType] = useState('prd');
  const [projectName, setProjectName] = useState(''), [sourceText, setSourceText] = useState(''), [url, setUrl] = useState(''), [dynamic, setDynamic] = useState(false), [purpose, setPurpose] = useState('current'), [history, setHistory] = useState<Obj[]>([]);
  const [rename, setRename] = useState(''), [outcome, setOutcome] = useState('summary'), [pendingOption, setPendingOption] = useState<Obj | null>(null), [showAdvanced, setShowAdvanced] = useState(false), [showAllQuestions, setShowAllQuestions] = useState(false), [mobilePane, setMobilePane] = useState('discussion');
  const [artifacts, setArtifacts] = useState<Obj>({ document_artifact: [] }), [selectedDocId, setSelectedDocId] = useState(''), [pendingGrant, setPendingGrant] = useState<Obj | null>(null);
  const currentProject = useRef<string | null>(null), refreshSerial = useRef(0), drafts = useRef<Record<string, string>>({});
  useDialog(Boolean(rename), () => setRename(''));
  useDialog(Boolean(pendingOption), () => setPendingOption(null));
  async function refresh(id = p?.id, switching = false) {
    if (!switching && currentProject.current !== (id || null)) return;
    const switched = switching && currentProject.current !== (id || null);
    if (switching) currentProject.current = id || null;
    if (switched) { setArtifacts({ document_artifact: [] }); setHistory([]); setSelectedDocId(''); }
    const serial = ++refreshSerial.current;
    const [projectList, modelState, projectState, runState] = await Promise.all([api<ProjectSummary[]>('/projects'), api<Obj>('/models'), id ? api<Project>('/projects/' + id) : Promise.resolve(null), id ? api<Run[]>('/projects/' + id + '/runs') : Promise.resolve([] as Run[])]);
    if (serial !== refreshSerial.current || currentProject.current !== (id || null)) return;
    setProjects(projectList); setModels(modelState); setP(projectState); setRuns(runState);
    if (switched && projectState) setStage(projectState.items.length ? 'clarify' : 'ingest');
  }
  async function act(fn: () => Promise<unknown>) { setError(''); setBusy(true); try { await fn(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  useEffect(() => { api('/session').then(x => { setCsrf(x.csrf); setLogged(true); refresh(); }).catch(() => { }); }, []);
  useEffect(() => { if (!p || !runs.some(r => ['queued', 'running'].includes(r.status))) return; const timer = setInterval(() => refresh(p.id).catch(e => setError(e.message)), 1200); return () => clearInterval(timer); }, [p?.id, runs.some(r => ['queued', 'running'].includes(r.status))]);
  const root = p ? '/projects/' + p.id : '';
  const rev = { expected_revision: p?.revision };
  async function mutate(path: string, body: Obj, method = 'POST') { const projectId = p?.id; await api(root + path, method, { ...rev, ...body }); if (currentProject.current === projectId) await refresh(projectId); }
  async function runAction() {
    await api(root + '/runs', 'POST', { ...rev, stage, message, document_type: docType });
    if (currentProject.current === p?.id) await refresh(p.id);
  }
  if (!logged) return <div className="login"><div className="brand-mark">需</div><p className="eyebrow">REQUIREMENTS AGENT</p><h1>把零散想法，变成清晰需求。</h1><p className="muted">本地产品工作台 · 材料、方案、PRD 与交接</p><form onSubmit={e => { e.preventDefault(); act(async () => { const x = await api('/session/login', 'POST', { key: token }); setCsrf(x.csrf); setLogged(true); setToken(''); await refresh(); }); }}><label>本机访问令牌<input type="password" value={token} onChange={e => setToken(e.target.value)} placeholder="从启动终端复制访问令牌" autoComplete="off" /></label><button className="primary" disabled={busy}>进入工作台</button></form>{error && <p role="alert" className="error">{error}</p>}<small>模型 API Key 可从项目根目录 .env 自动读取；登录后在“模型设置”查看状态。</small></div>;
  return <AppShell sidebar={<aside className="sidebar"><div className="brand"><span className="brand-mark">需</span><strong>需求 Agent</strong><span className="version">1.1</span></div>
    <ProjectSwitcher projects={projects} currentId={p?.id} name={projectName} setName={setProjectName} busy={busy} onCreate={() => act(async () => { const x = await api('/projects', 'POST', { name: projectName }); setProjectName(''); if (p) drafts.current[p.id] = message; setMessage(drafts.current[x.id] || ''); await refresh(x.id, true); setTab('conversation'); })} onSwitch={id => { if (p) drafts.current[p.id] = message; setMessage(drafts.current[id] || ''); setTab('conversation'); act(() => refresh(id, true)); }} />
    {p && <nav className="side-nav" aria-label="项目导航">{[['conversation', '讨论工作台', '◫'], ['sources', '参考材料', '▤'], ['prototype', '原型画布', '▧'], ['documents', '需求文档', '▣'], ['confirm', '确认与交接', '✓'], ['history', '版本记录', '◷']].map(([id, name, icon]) => <button key={id} className={tab === id ? 'active' : ''} onClick={() => { setTab(id); if (id === 'history') act(async () => { const value = await api<Obj[]>(root + '/history'); if (currentProject.current === p.id) setHistory(value); }); if (id === 'documents') act(async () => { const value = await api<Obj>(root + '/artifacts'); if (currentProject.current === p.id) setArtifacts(value); }); }} title={name}><span aria-hidden="true">{icon}</span><span className="nav-label">{name}</span></button>)}</nav>}
    <div className="sidebar-bottom"><button className={tab === 'settings' ? 'active' : ''} onClick={() => setTab('settings')} title="模型设置"><span aria-hidden="true">⚙</span><span className="nav-label">模型设置</span></button><small>数据保存在本机</small></div></aside>}>
    <header className="topbar"><div><p className="eyebrow">产品需求工作台</p><h1>{tab === 'settings' ? '模型与调用预算' : p?.name || '开始一个需求项目'}</h1></div>{p && <div className="header-actions"><span className="pill">草稿 v{p.revision}</span><span className="pill">{runs.some(r => ['queued', 'running'].includes(r.status)) ? '运行中' : '已保存'}</span><button onClick={() => setTab('confirm')}>查看确认条件</button><select aria-label="工作模式" value={p.mode} onChange={e => act(() => mutate('', { mode: e.target.value }, 'PATCH'))}><option value="explore">探索模式</option><option value="converge">收敛模式</option></select><button onClick={() => setRename(p.name)}>重命名</button></div>}</header>
    {rename && <div className="modal-backdrop"><form className="modal" role="dialog" aria-modal="true" aria-label="重命名项目" onSubmit={e => { e.preventDefault(); act(async () => { await mutate('', { name: rename }, 'PATCH'); setRename(''); }); }}><h2>重命名项目</h2><label>项目名称<input value={rename} onChange={e => setRename(e.target.value)} required /></label><div className="toolbar"><button type="button" onClick={() => setRename('')}>取消</button><button className="primary">保存</button></div></form></div>}
    {error && <div className="error banner" role="alert">{error}<button onClick={() => setError('')}>关闭</button></div>}
    {tab === 'settings' ? <ModelSettings models={models} busy={busy} act={act} refresh={refresh} /> : !p ? <section className="welcome"><p className="eyebrow">从材料开始，而非从空白文档开始</p><h2>让需求逐步清晰。</h2><p>上传现状材料，比较可选方向，澄清关键规则。<br />先看页面方案，再确认可追溯的交付版本。</p><div className="steps"><div><b>01</b> 材料与理解</div><div><b>02</b> 方案与澄清</div><div><b>03</b> 评审与交接</div></div><p className="muted">在左侧创建第一个项目。</p></section> : <>
      <div className="workspace">
        {tab === 'conversation' && <div className={'workbench-grid ' + (mobilePane === 'discussion' ? 'show-discussion' : 'show-artifacts')}><div className="mobile-switch"><button onClick={() => setMobilePane('discussion')}>讨论</button><button onClick={() => setMobilePane('artifacts')}>成果</button></div><ConversationPanel project={p} message={message} setMessage={value => { if (p) drafts.current[p.id] = value; setMessage(value); }} stage={stage} setStage={setStage} docType={docType} setDocType={setDocType} onRun={() => act(runAction)} runActive={runs.some(r => ['queued', 'running'].includes(r.status))} busy={busy} onAnswer={(id, answer) => act(() => mutate('/questions/' + id, { answer }))} showAdvanced={showAdvanced} setShowAdvanced={setShowAdvanced} showAllQuestions={showAllQuestions} setShowAllQuestions={setShowAllQuestions} /><ArtifactTabs project={p} tab={outcome} setTab={setOutcome} onOption={(option, status) => setPendingOption({ ...option, nextStatus: status, selectedIds: [] })} onItem={(item, status) => act(() => mutate('/items/' + item.id, { selection_status: status }))} onEditItem={(item, statement) => act(() => mutate('/items/' + item.id, { selection_status: item.selection_status, statement }))} onNavigate={setTab} onStage={s => { setStage(s); setShowAdvanced(true); }} onActivate={id => act(() => mutate('/ui-candidates/' + id + '/activate', {}))} onReject={id => act(() => mutate('/ui-candidates/' + id + '/reject', {}))} previewUrl={'/api' + root + '/prototype'} runs={runs} models={models} onCancel={id => act(async () => { await api(root + '/runs/' + id + '/cancel', 'POST'); await refresh(); })} onResume={id => act(() => mutate('/runs/' + id + '/resume', {}))} /></div>}
        {pendingOption && <div className="modal-backdrop"><div className="modal" role="dialog" aria-modal="true" aria-label="核对方案操作"><h2>{pendingOption.nextStatus === 'items' ? '采纳指定关联条目' : '记录讨论方向'}</h2><p>{pendingOption.name}</p>{pendingOption.nextStatus === 'items' ? <><p>只采纳明确勾选的条目；关联本身不代表授权。</p><div className="choice-list">{pendingOption.proposed_item_refs.map((id: string) => { const item = p.items.find((i: Obj) => i.id === id); const excerpts = item?.source_refs?.flatMap((ref: Obj) => p.sources.find((s: Obj) => s.id === ref.source_id)?.excerpts.filter((ex: Obj) => ex.id === ref.excerpt_id).map((ex: Obj) => ex.text) || []) || []; return <label key={id} className="summary-item"><input type="checkbox" checked={pendingOption.selectedIds.includes(id)} onChange={e => setPendingOption({ ...pendingOption, selectedIds: e.target.checked ? [...pendingOption.selectedIds, id] : pendingOption.selectedIds.filter((x: string) => x !== id) })} /><strong>{item?.title || id}</strong><p>{item?.statement || '原文缺失'}</p><small>{id} · 属性 {item?.epistemic_status || '未知'} · 当前 {statusNames[item?.selection_status] || '未知'}</small><p>来源：{excerpts.join('；') || '来源不可见，不能采纳'}</p></label>; })}</div></> : <p className="notice">{pendingOption.nextStatus === 'selected' ? '仅选为后续讨论方向。关联条目的采纳状态、事实或假设属性，以及未答问题均保持不变。' : '只改变此方案的讨论状态；此前独立采纳的条目不受影响。'}</p>}{p.questions.some((q: Obj) => q.blocking && q.status !== 'answered') && <p className="notice">关键规则仍未决定，此方向不代表可开发方案已完成。</p>}<div className="toolbar"><button onClick={() => setPendingOption(null)}>取消</button><button className="primary" disabled={busy || (pendingOption.nextStatus === 'items' && !pendingOption.selectedIds.length)} onClick={() => act(async () => { if (pendingOption.nextStatus === 'items') await mutate('/options/' + pendingOption.id + '/items', { item_ids: pendingOption.selectedIds }); else await mutate('/options/' + pendingOption.id + '/direction', { direction_status: pendingOption.nextStatus }); setPendingOption(null); })}>确认提交</button></div></div></div>}
        {tab === 'sources' && <SourcePanel p={p} models={models} purpose={purpose} setPurpose={setPurpose} sourceText={sourceText} setSourceText={setSourceText} url={url} setUrl={setUrl} dynamic={dynamic} setDynamic={setDynamic} busy={busy} act={act} mutate={mutate} refresh={refresh} root={root} pendingGrant={pendingGrant} setPendingGrant={setPendingGrant} />}
        {tab === 'prototype' && <PrototypeCanvas project={p} url={'/api' + root + '/prototype'} onStage={s => { setStage(s); setTab('conversation'); setOutcome('prototype'); }} onActivate={id => act(() => mutate('/ui-candidates/' + id + '/activate', {}))} onReject={id => act(() => mutate('/ui-candidates/' + id + '/reject', {}))} />}
        {tab === 'documents' && <DocumentStudio p={p} docType={docType} setDocType={setDocType} selectedDocId={selectedDocId} setSelectedDocId={setSelectedDocId} artifacts={artifacts} setStage={setStage} setShowAdvanced={setShowAdvanced} setTab={setTab} setOutcome={setOutcome} root={root} act={act} mutate={mutate} />}
        {tab === 'confirm' && <ConfirmationPanel p={p} busy={busy} setBusy={setBusy} setError={setError} setTab={setTab} setStage={setStage} setShowAdvanced={setShowAdvanced} root={root} act={act} refresh={refresh} />}
        {tab === 'history' && <VersionHistory history={history} />}
      </div></>}
  </AppShell>;
}
createRoot(document.getElementById('root')!).render(<App />);
