import React, { useEffect, useRef, useState } from 'react';
import { Project, JsonObject as Obj } from './api';
import { useDirty, useNavigation } from './editing';

const scope: Obj = {current_state:'当前现状',users:'目标使用者',value:'问题与改动价值',change_scope:'本次改动',preserve_scope:'保持不变',out_of_scope:'暂不涉及',priority:'优先级与依据'};
const behavior: Obj = {actor:'谁操作',entry:'入口及前置条件',flow:'主要流程',data:'业务数据',permissions:'权限约束',result:'操作结果',exceptions:'边界和异常'};
type Props={p:Project;phase:number;busy:boolean;mutate:(path:string,body:Obj)=>Promise<unknown>;go:(n:number)=>void;onAnalyze?:()=>void;onSources?:()=>void;onHelp?:(target:Obj)=>void};

export function ProductCheckpoint({p,phase,busy,mutate,go,onAnalyze,onSources,onHelp}:Props) {
  const init=()=>phase===0?((p as Obj).intake||{text:p.product_context?.intent||'',platform:[p.product_context?.product,p.product_context?.module].filter(Boolean).join(' / '),preserved:p.product_context?.preserve_scope||''}):phase===3?(p.sketch_review||{applicable:true}):{...p.product_context_proposal,...p.product_context};
  const [values,setValues]=useState<Obj>(init),[ids,setIds]=useState<string[]>(p.product_context?.scope_ids||[]),[dirty,setDirty]=useState(false),[editing,setEditing]=useState(false),[error,setError]=useState(''),[saving,setSaving]=useState(false);
  const base=useRef(p.revision),state=p.product_flow?.[phase],navigate=useNavigation();
  useEffect(()=>{if(!dirty){setValues(init());setIds(p.product_context?.scope_ids||[]);base.current=p.revision;}},[p,phase,dirty]);
  const fields=phase===1?scope:phase===3?(values.applicable===false?{reason:'无界面变化的原因'}:{changes:'新增或修改区域',preserved:'原有保持部分',behavior:'入口、操作、结果与重要未决项'}):{};
  const edit=(key:string,value:unknown)=>{if(!dirty)base.current=p.revision;setValues(v=>({...v,[key]:value}));setDirty(true);};
  async function save(){setError('');setSaving(true);try{await mutate(phase===0?'/intake':phase===3?'/sketch-review':'/product-context',{expected_revision:base.current,...(phase===0?{text:values.text||'',platform:values.platform||'',preserved:values.preserved||''}:phase===3?{applicable:values.applicable!==false,reason:values.reason||'',changes:values.changes||'',preserved:values.preserved||'',behavior:values.behavior||''}:{values:Object.fromEntries(Object.keys(fields).map(k=>[k,values[k]||''])),scope_ids:ids})});setDirty(false);setEditing(false);}finally{setSaving(false);}}
  const discard=()=>{setDirty(false);setValues(init());setIds(p.product_context?.scope_ids||[]);setEditing(false);};
  useDirty(p.id+'-checkpoint-'+phase,dirty,'第'+(phase+1)+'步编辑',save,discard);
  async function attempt(fn:()=>Promise<unknown>){try{await fn();}catch(e){setError((e as Error).message);}}
  async function check(){await mutate('/stage-checks/'+(phase+1),{expected_hash:state?.content_hash});go(phase+1);}
  const locked=busy||saving;
  return <article className={'card checkpoint step-check-'+phase}>
    <div className="section-heading"><h2>{['描述这次想解决的问题','核对本次改动范围','核对业务行为与验收','核对草图表达','核对两份交付文档'][phase]}</h2><span className="pill">{dirty?'未保存':state?.complete?(phase===0?'已提供':'已核对'):state?.needs_recheck?'需重新核对':'待核对'}</span></div>
    {phase===0&&<><p className="muted">先描述您要解决的问题，资料可随时补充。分析后核对现状、目标与改动范围。</p><div className="intake-layout"><div className="intake-fields"><label className="intake-row"><span><b>1. 现有平台 / 页面</b><small>涉及的系统、页面或模块，已在资料中说明的可不重复填写。</small></span><textarea rows={3} value={values.platform||''} onChange={e=>edit('platform',e.target.value)} placeholder="描述本次改动所在的现有平台或页面"/></label><label className="intake-row"><span><b>2. 本次想新增或修改什么</b><small>核心诉求。零散信息也可以，不必先整理成完整需求。</small></span><textarea aria-label="核心诉求" rows={4} value={values.text||''} onChange={e=>edit('text',e.target.value)} placeholder="希望解决什么问题，新增或修改什么？"/></label><label className="intake-row"><span><b>3. 保持不变 / 暂不涉及</b><small>可选。帮助界定本次改动的边界，未知可以留空。</small></span><textarea rows={3} value={values.preserved||''} onChange={e=>edit('preserved',e.target.value)} placeholder="哪些内容保持原状，哪些暂时不做？"/></label></div><aside className="intake-guide"><h3>✧ AI 将帮助你整理为</h3><p>基于你提供的材料与诉求，形成供你核对的内容。</p>{[['▤','现状摘要','理解现有页面与流程'],['◎','改动目标','梳理本次目标与价值'],['◇','保持项','明确不能擅自改变的内容'],['?','待补充信息','缺失信息保持待定']].map(([icon,title,desc])=><section key={title}><span>{icon}</span><div><b>{title}</b><p>{desc}</p></div></section>)}</aside></div><div className="material-strip"><h3>现有资料</h3>{p.sources.length?p.sources.map(s=><button key={s.id} onClick={onSources}>{s.title} · {s.excluded?'已排除':({read:'已读取',partial:'部分读取',failed:'读取失败',awaiting_vision:'待视觉分析'} as Obj)[s.parse_status]||s.parse_status}</button>):<p>可添加截图、文档、文字或公开网址。上传成功不代表已理解。</p>}<button onClick={onSources}>＋ 添加现有资料</button></div><div className="step-actions"><span className="muted">先保存输入，再核对模型任务及材料范围。</span><button disabled={locked||(!dirty&&!!(p as Obj).intake)} onClick={()=>attempt(save)}>保存输入</button><button className="primary" disabled={locked||dirty||!state?.complete} onClick={onAnalyze}>分析资料与诉求</button></div>{p.messages.some(m=>m.role==='assistant'&&m.stage==='ingest')&&<button onClick={()=>go(1)}>查看已有分析结果 →</button>}</>}
    {phase===1&&<><p className="muted">先读结果，再修改偏差。核对范围不会自动采纳建议。</p><div className="scope-cards">{['current_state','change_scope','preserve_scope','out_of_scope'].map(key=><section key={key}><div className="section-heading"><h3><span className="tone-icon">{({current_state:'▤',change_scope:'◎',preserve_scope:'◇',out_of_scope:'?' } as Obj)[key]}</span>{scope[key]}</h3><button onClick={()=>setEditing(true)}>编辑</button></div><p>{values[key]||'资料不足，待补充'}</p><small>{p.product_context?.[key]===values[key]?'已保存的核对内容':'分析建议 · 待核对'}</small></section>)}</div><div className="scope-facts">{['users','value','priority'].map(key=><p key={key}><b>{scope[key]}：</b>{values[key]||'待核对'}</p>)}</div><button onClick={()=>setEditing(!editing)}>{editing?'收起编辑':'编辑现状与范围'}</button>{editing&&<div className="inline-editor">{Object.entries(fields).map(([key,label])=><label key={key}>{String(label)}<textarea rows={2} value={values[key]||''} onChange={e=>edit(key,e.target.value)}/></label>)}</div>}<fieldset><legend>本期需求范围</legend>{p.items.filter(i=>i.kind==='requirement'&&i.applies_to==='to_be').map(i=><label className="scope-row" key={i.id}><input type="checkbox" checked={ids.includes(i.id)} onChange={e=>{if(!dirty)base.current=p.revision;setIds(e.target.checked?[...ids,i.id]:ids.filter(id=>id!==i.id));setDirty(true);}}/><span><b>{i.title}</b><small>{i.id} · v{i.content_version||1} · {({new:'新增',modified:'修改',preserved:'保持',existing:'现状'} as Obj)[i.change_type]||'性质待核对'}</small><p>{i.statement}</p></span></label>)}{!p.items.some(i=>i.kind==='requirement')&&<p>还没有独立需求。可返回分析资料，或在下方补充一条候选需求。</p>}</fieldset><div className="toolbar"><button disabled={locked} onClick={()=>attempt(save)}>保存范围核对</button>{dirty&&<button onClick={()=>navigate(discard)}>取消编辑</button>}</div></>}
    {phase===2&&<><p>行为说明与验收来自当前条目，不会用通用规则补齐空缺。</p>{p.items.filter(i=>i.kind==='requirement'&&p.product_context?.scope_ids?.includes(i.id)).map(i=><BehaviorEditor key={i.id} item={i} mutate={mutate} busy={locked} revision={p.revision}/>)}<details><summary>本期以外的未决事项及范围决定</summary>{p.questions.filter(q=>q.status!=='answered').map(q=><QuestionScope key={q.id} question={q} mutate={mutate}/>)}</details><RequirementRelations p={p} mutate={mutate}/></>}
    {phase===3&&<><p>只核对功能、入口、操作、保持项与未决事项，布局细节交由 UI 设计继续完善。</p><div className="sketch-notes">{[['changes','新增或修改'],['preserved','保持不变'],['behavior','行为与待定']].map(([key,label])=><section key={key}><h3>{label}</h3><p>{values[key]||'待核对说明'}</p></section>)}<section><h3>关联需求编号</h3>{p.items.filter(i=>i.kind==='requirement'&&p.product_context?.scope_ids?.includes(i.id)).map(i=><p key={i.id}>{i.id} · v{i.content_version||1}<br/>{i.title}</p>)}</section></div><button onClick={()=>setEditing(!editing)}>{editing?'收起草图说明编辑':'调整草图核对说明'}</button>{editing&&<div className="inline-editor"><label className="check"><input type="checkbox" checked={values.applicable!==false} onChange={e=>edit('applicable',e.target.checked)}/>本次涉及界面或交互变化</label>{Object.entries(fields).map(([key,label])=><label key={key}>{String(label)}<textarea rows={2} value={values[key]||''} onChange={e=>edit(key,e.target.value)}/></label>)}<button disabled={locked} onClick={()=>attempt(save)}>保存草图核对说明</button></div>}</>}
    {phase===4&&<><p>MRD 与 PRD 分别核对各自版本，两份有效后才能进入交接。</p><div className="document-pair">{['mrd','prd'].map(k=><div key={k}><strong>{k.toUpperCase()}</strong><p>{p.documents[k]?`文档 v${p.documents[k].document_version||'未记录'} · 底稿 v${p.documents[k].draft_revision}`:'尚未生成'}</p><p>{(p as Obj).document_review_status?.[k]?.reviewed?'当前版本已核对':'当前版本尚未核对'}</p></div>)}</div></>}
    {error&&<div role="alert" className="error"><p>{error} · 输入仍保留。</p>{/版本|变化/.test(error)&&<details><summary>查看已刷新内容并处理冲突</summary><p>当前底稿 v{p.revision}；编辑基于 v{base.current}。请对照下面内容，合并需要保留的修改。</p>{Object.entries(init()).filter(([,v])=>typeof v==='string').map(([k,v])=><p key={k}>{scope[k]||k}：{String(v)}</p>)}<button onClick={()=>{base.current=p.revision;setError('');}}>已核对差异，保留编辑并继续修改</button></details>}</div>}
    {phase>0&&<>{state&&!state.available&&<p className="notice">可提前查看，继续前请先完成前序核对。<button onClick={()=>go(Math.max(0,phase-1))}>返回前一步</button></p>}{!!state?.missing.length&&<details className="notice"><summary>继续前还需核对 {state?.missing.length} 项</summary><ul>{state?.missing.map(x=><li key={x}>{x}</li>)}</ul></details>}<div className="step-actions"><button onClick={()=>go(phase-1)}>上一步</button><span>{dirty?'请先保存修改':'保存与核对均不调用模型'}</span><button className="primary" disabled={locked||dirty||!state?.available||!!state?.missing.length} onClick={()=>attempt(check)}>{['','确认范围并进入下一步','核对规则并继续','确认草图并继续','完成文档评审并进入交接'][phase]} →</button></div></>}
  </article>;
}

export function QuestionList({p,mutate,busy,onHelp}:{p:Project;mutate:Props['mutate'];busy:boolean;onHelp:(target:Obj)=>void}){
 const [answers,setAnswers]=useState<Obj>({}),[unknown,setUnknown]=useState<string[]>([]),[error,setError]=useState(''),[saving,setSaving]=useState(false);const base=useRef(p.revision);
 const dirty=Object.keys(answers).length>0;
 async function save(){const values=Object.fromEntries(Object.entries(answers).filter(([,v])=>String(v).trim()));if(Object.keys(values).length!==Object.keys(answers).length)throw Error('空白回答不会被视为已回答，请填写或选择保留未知。');await mutate('/answers',{answers:values,expected_revision:base.current});setAnswers({});}
 useDirty(p.id+'-answers',dirty,'问题回答',save,()=>setAnswers({}));
 function edit(id:string,text:string){if(!dirty)base.current=p.revision;setAnswers(v=>({...v,[id]:text}));}
 function card(q:Obj){return <article className="question-item" key={q.id}><div className="question-description"><div className="section-heading"><h3>{q.question}</h3><span className="pill">{q.status==='answered'?'已回答':q.blocking?'影响第'+(q.blocking_stage||3)+'步':'待决定'}</span></div><p className="muted">{q.why}</p><small>{q.id} · 关联：{q.affected_requirements?.map((r:Obj)=>r.id).join('、')||q.related_refs?.join('、')||'尚未关联'}</small></div><div className="question-answer"><label>你的回答<textarea rows={2} aria-label={q.question} value={answers[q.id]??q.answer??''} onChange={e=>edit(q.id,e.target.value)}/></label></div><div className="question-suggestion">{q.options?.length>0&&<div className="choice-list">{q.options.map((x:string)=><button key={x} onClick={()=>edit(q.id,x)}>填入建议：{x}</button>)}</div>}<div className="toolbar"><button onClick={()=>{setUnknown(v=>v.includes(q.id)?v:[...v,q.id]);setAnswers(v=>{const n={...v};delete n[q.id];return n;});}}>暂不确定，保留未知</button><button onClick={()=>onHelp({kind:'question',id:q.id,label:q.question})}>帮我分析这个问题</button></div>{unknown.includes(q.id)&&<p className="notice">仍未解决，不会自动解除阻塞；可以继续查看其他步骤。</p>}</div></article>;}
 return <article className="card"><h2>需要你决定的问题</h2><p className="muted">建议只填入编辑区。保存后才会更新回答，未知保持未知。</p>{[...p.items.filter(i=>i.kind==='requirement').map(i=>({id:i.id,label:i.id+'｜'+i.title})),{id:'unbound',label:'尚未关联具体需求'}].map(group=>{const questions=p.questions.filter(q=>q.status!=='answered'&&!q.out_of_scope_reason).filter(q=>{const actual=p.items.find(i=>i.kind==='requirement'&&((q.related_refs||[]).includes(i.id)||(q.affected_requirements||[]).some((r:Obj)=>r.id===i.id)));return (actual?.id||'unbound')===group.id;});return questions.length?<section className="question-group" key={group.id}><h3>{group.label} · {questions.length} 项待决定</h3>{questions.map(card)}</section>:null;})}{!p.questions.length&&<p>尚无澄清问题。可先核对资料理解与本期范围。</p>}<details><summary>已回答 · {p.questions.filter(q=>q.status==='answered').length}（可修改）</summary>{p.questions.filter(q=>q.status==='answered').map(card)}</details>{error&&<p role="alert" className="error">{error}</p>}<button className="primary" disabled={!dirty||busy||saving} onClick={async()=>{setSaving(true);try{await save();setError('');}catch(e){setError((e as Error).message);}finally{setSaving(false);}}}>保存本次回答</button></article>;
}

function RequirementRelations({p,mutate}:{p:Project;mutate:Props['mutate']}){
  const [source,setSource]=useState(''),[target,setTarget]=useState(''),[relation,setRelation]=useState('refines'),[error,setError]=useState('');
  const reqs=p.items.filter(i=>i.kind==='requirement');
  return <details><summary>需求的父子、细化与依赖关系</summary><p>拆分或取代时保留原编号，各子需求有自己的编号。关系不代表实现或测试通过。</p>{(p.requirement_relations||[]).map((r:Obj,n:number)=><p key={n}>{r.source.id} v{r.source.version} → {r.type} → {r.target.id} v{r.target.version}</p>)}{reqs.length>1&&<><label>起始需求<select value={source} onChange={e=>setSource(e.target.value)}><option value="">选择需求</option>{reqs.map(i=><option key={i.id} value={i.id}>{i.id}｜{i.title}</option>)}</select></label><label>关系<select value={relation} onChange={e=>setRelation(e.target.value)}>{[['parent_of','是其父需求'],['refines','细化'],['replaces','取代'],['depends_on','依赖']].map(([k,n])=><option key={k} value={k}>{n}</option>)}</select></label><label>目标需求<select value={target} onChange={e=>setTarget(e.target.value)}><option value="">选择需求</option>{reqs.map(i=><option key={i.id} value={i.id}>{i.id}｜{i.title}</option>)}</select></label><button disabled={!source||!target||source===target} onClick={async()=>{try{await mutate('/requirement-relations',{source_id:source,target_id:target,relation});setError('');}catch(e){setError((e as Error).message);}}}>记录关系</button></>}{error&&<p role="alert">{error}</p>}<p><a href={'/api/projects/'+p.id+'/requirements-exchange'} download={p.name+'-需求交换.json'}>导出结构化需求与关系</a>（当前草稿；正式交接使用确认基线）</p></details>;
}

function BehaviorEditor({item,mutate,busy,revision}:{item:Obj;mutate:Props['mutate'];busy:boolean;revision:number}){
  const [values,setValues]=useState<Obj>(item.behavior||{}),[kind,setKind]=useState(item.change_type||'modified'),[dirty,setDirty]=useState(false),[error,setError]=useState('');
  useEffect(()=>{if(!dirty){setValues(item.behavior||{});setKind(item.change_type||'modified');}},[item,dirty]);
  const base=useRef(revision); useEffect(()=>{if(!dirty)base.current=revision;},[revision,dirty]);
  const save=async()=>{await mutate('/items/'+item.id+'/behavior',{values,change_type:kind,expected_revision:base.current});setDirty(false);setError('');};
  useDirty(item.id+'-behavior',dirty,'需求行为 '+item.title,save,()=>{setValues(item.behavior||{});setDirty(false);});
  return <details><summary>{item.id}｜{item.title} · v{item.content_version||1}{dirty?' · 未保存':''}</summary><p>{item.statement}</p><label>本次性质<select value={kind} onChange={e=>{setKind(e.target.value);setDirty(true);}}>{[['new','新增'],['modified','修改'],['preserved','保持约束'],['existing','现状']].map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label>{Object.entries(behavior).map(([key,label])=><label key={key}>{String(label)}<textarea value={values[key]||''} onChange={e=>{setValues(v=>({...v,[key]:e.target.value}));setDirty(true);}}/></label>)}{error&&<p role="alert">{error}</p>}<button disabled={busy||!dirty} onClick={async()=>{try{await save();}catch(e){setError((e as Error).message);}}}>保存此需求行为</button></details>;
}
function QuestionScope({question:q,mutate}:{question:Obj;mutate:Props['mutate']}){
  const [reason,setReason]=useState(q.out_of_scope_reason||''),[error,setError]=useState('');
  return <details><summary>{q.question}{q.out_of_scope_reason?' · 已移出本期，仍未知':''}</summary><p>影响需求：{q.affected_requirements?.map((r:Obj)=>r.id).join('、')||q.related_refs?.join('、')||'尚待关联范围'}</p><p>{q.why} · 影响第{q.blocking_stage||3}步</p><label>明确移出本期的理由（清空可恢复）<textarea value={reason} onChange={e=>setReason(e.target.value)}/></label><p>不改变原问题、答案或条目采纳状态；本期仍依赖的规则不得移出。</p><button onClick={async()=>{try{await mutate('/questions/'+q.id+'/scope',{out_of_scope_reason:reason});}catch(e){setError((e as Error).message);}}}>保存范围决定</button>{error&&<p role="alert">{error}</p>}</details>;
}
