import React, { useEffect, useRef, useState } from 'react';
import { Project, JsonObject as Obj } from './api';
import { useDirty, useNavigation } from './editing';
import { Icon } from './ui-icons';

const scope: Obj = {current_state:'当前现状',users:'目标使用者',value:'问题与改动价值',change_scope:'本次改动',preserve_scope:'保持不变',out_of_scope:'暂不涉及',priority:'优先级与依据'};
const behavior: Obj = {actor:'谁操作',entry:'入口及前置条件',flow:'主要流程',data:'业务数据',permissions:'权限约束',result:'操作结果',exceptions:'边界和异常'};
type Props={p:Project;phase:number;busy:boolean;mutate:(path:string,body:Obj)=>Promise<unknown>;go:(n:number)=>void;onAnalyze?:()=>Promise<void>;onCandidate?:()=>void;onItem?:(item:Obj,status:string)=>void;onSource?:(refs:Obj[])=>void;onSources?:()=>void;onHelp?:(target:Obj)=>void};

export function ProductCheckpoint({p,phase,busy,mutate,go,onAnalyze,onSources,onHelp,onCandidate,onItem,onSource}:Props) {
  const init=()=>phase===0?((p as Obj).intake||{text:p.product_context?.intent||'',platform:[p.product_context?.product,p.product_context?.module].filter(Boolean).join(' / '),preserved:p.product_context?.preserve_scope||''}):phase===3?(p.sketch_review||{applicable:true}):{...p.product_context_proposal,...p.product_context};
  const [values,setValues]=useState<Obj>(init),[ids,setIds]=useState<string[]>(p.product_context?.scope_ids||[]),[dirty,setDirty]=useState(false),[editing,setEditing]=useState<string|null>(null),[error,setError]=useState(''),[saving,setSaving]=useState(false);
  const base=useRef(p.revision),state=p.product_flow?.[phase],navigate=useNavigation();
  useEffect(()=>{if(!dirty){setValues(init());setIds(p.product_context?.scope_ids||[]);base.current=p.revision;}},[p,phase,dirty]);
  const fields=phase===1?scope:phase===3?(values.applicable===false?{reason:'无界面变化的原因'}:{changes:'新增或修改区域',preserved:'原有保持部分',behavior:'入口、操作、结果与重要未决项'}):{};
  const edit=(key:string,value:unknown)=>{if(!dirty)base.current=p.revision;setValues(v=>({...v,[key]:value}));setDirty(true);};
  async function save(){setError('');setSaving(true);try{await mutate(phase===0?'/intake':phase===3?'/sketch-review':'/product-context',{expected_revision:base.current,...(phase===0?{text:values.text||'',platform:values.platform||'',preserved:values.preserved||''}:phase===3?{applicable:values.applicable!==false,reason:values.reason||'',changes:values.changes||'',preserved:values.preserved||'',behavior:values.behavior||''}:{values:Object.fromEntries((phase===1&&editing&&editing!=='facts'?[editing]:phase===1&&editing==='facts'?['users','value','priority']:Object.keys(fields)).map(k=>[k,values[k]||''])),scope_ids:ids})});setDirty(false);setEditing(null);}finally{setSaving(false);}}
  const discard=()=>{setDirty(false);setValues(init());setIds(p.product_context?.scope_ids||[]);setEditing(null);};
  useDirty(p.id+'-checkpoint-'+phase,dirty,'第'+(phase+1)+'步编辑',save,discard);
  async function attempt(fn:()=>Promise<unknown>){try{await fn();}catch(e){setError((e as Error).message);}}
  async function check(){await mutate('/stage-checks/'+(phase+1),{expected_hash:state?.content_hash});go(phase+1);}
  const locked=busy||saving;
  return <article className={'card checkpoint step-check-'+phase}>
    <div className="section-heading"><h2>{['描述这次想解决的问题','核对本次改动范围','核对业务行为与验收','核对草图表达','核对两份交付文档'][phase]}</h2><span className="pill">{dirty?'未保存':state?.complete?(phase===0?'已提供':'已核对'):state?.needs_recheck?'需重新核对':'待核对'}</span></div>
    {phase===0&&<>
      <div className="intake-layout"><div className="intake-fields">
        <label className="intake-row"><span><b>1. 现有平台 / 页面</b><small>请描述涉及的系统、平台或具体页面，已有资料可不重复填写。</small></span><textarea rows={3} value={values.platform||''} onChange={e=>edit('platform',e.target.value)} placeholder="例如：目前使用的平台、希望改动的页面…"/></label>
        <label className="intake-row"><span><b>2. 本次想新增或修改什么 <em>*</em></b><small>请描述你的需求、期望达到的目标或需要解决的问题。</small></span><textarea aria-label="核心诉求" rows={3} value={values.text||''} onChange={e=>edit('text',e.target.value)} placeholder="描述这次想解决的问题，零散信息也可以…"/></label>
        <label className="intake-row"><span><b>3. 保持不变 / 暂不涉及</b><small>请说明哪些内容保持不变，避免不必要的改动。</small></span><textarea rows={3} value={values.preserved||''} onChange={e=>edit('preserved',e.target.value)} placeholder="哪些内容保持原状，哪些暂时不做…"/></label>
        <section className="intake-materials"><h3>4. 相关资料（可选）</h3><p>添加页面截图、需求文档或参考链接，帮助理解本次需求。</p><div className="material-cards"><button className="material-upload" onClick={onSources}><Icon name="upload"/><span>点击添加相关资料</span><small>截图、文档、文字或公开网址 · 不支持拖拽</small></button>{p.sources.map(source=><button className="material-file" key={source.id} onClick={onSources}>{source.image_mime?<img src={'/api/projects/'+p.id+'/sources/'+source.id+'/image'} alt="材料缩略图"/>:<Icon name="document"/>}<span><b>{source.title}</b><small>{source.excluded?'已排除':({read:'已读取',partial:'部分读取',failed:'读取失败',awaiting_vision:'待视觉分析'} as Obj)[source.parse_status]||source.parse_status}</small></span></button>)}<button className="material-add" onClick={onSources}><b>＋</b>添加资料</button></div></section>
      </div><aside className="intake-guide"><h3>✦ AI 将帮助你整理为</h3><p>基于你的填写内容，整理出以下结果：</p>{[['document','现状摘要','梳理当前平台、页面现状与问题'],['target','改动目标','提炼本次改动的核心目标与价值'],['shield','保持项','识别需要保持不变的内容'],['question','待补充信息','发现可能缺失的关键信息']].map(([icon,title,desc],n)=><section className={'tone-'+n} key={title}><span className="tone-icon"><Icon name={icon}/></span><div><b>{title}</b><p>{desc}</p></div></section>)}</aside></div>
      <details className="assistant-note"><summary><Icon name="light"/><b>助手建议</b><span>先提供已知信息，缺失项稍后澄清。</span></summary><p>材料上传不等于已经理解。点击分析后先保存本次输入，再核对实际接收端、材料范围与调用预算；保存失败不会发送模型请求。</p></details>
      <div className="step-actions intake-actions"><button className="primary" disabled={locked||(!values.text?.trim()&&!values.platform?.trim()&&!p.sources.some(x=>!x.excluded))} onClick={()=>attempt(async()=>{if(dirty||!(p as Obj).intake)await save();await onAnalyze?.();})}>✦ 分析现状与诉求 →</button><button disabled={locked||(!dirty&&!!(p as Obj).intake)} onClick={()=>attempt(save)}>保存草稿</button><button onClick={onSources}>添加资料</button><span>{saving?'保存中…':dirty?'有未保存输入':(p as Obj).intake?'输入已保存':'输入后即可发起分析预检'}</span>{p.messages.some(m=>m.role==='assistant'&&m.stage==='ingest')&&<button onClick={()=>go(1)}>查看已有分析结果</button>}</div>
    </>}
    {phase===1&&<>
      <div className="scope-cards">{['current_state','change_scope','preserve_scope','out_of_scope'].map((key,n)=><section className={'tone-'+n} key={key}><div className="section-heading"><h3><span className="tone-icon"><Icon name={['document','target','shield','question'][n]}/></span>{({current_state:'现状摘要',change_scope:'改动目标',preserve_scope:'保持项',out_of_scope:'不在本期范围'} as Obj)[key]}</h3><button aria-label={'编辑'+scope[key]} onClick={()=>navigate(()=>setEditing(key))}><Icon name="edit"/>编辑</button></div>{editing===key?<div className="scope-card-editor"><label>{scope[key]}<textarea autoFocus rows={4} value={values[key]||''} onChange={e=>edit(key,e.target.value)}/></label><button disabled={locked} onClick={()=>attempt(save)}>保存此卡</button><button onClick={()=>navigate(discard)}>取消</button></div>:<p>{values[key]||'资料不足，待补充'}</p>}<small>{p.product_context?.[key]===values[key]?'已保存的核对内容':'分析建议 · 待核对'}</small></section>)}</div>
      <section className="scope-facts"><span className="tone-icon"><Icon name="question"/></span><div><h3>待补充信息</h3><small>帮助准确界定本次需求范围</small></div><div className="facts-list">{['users','value','priority'].map(key=><p key={key}><span>{values[key]?'✓':'○'}</span>{scope[key]}：{values[key]||'待补充'}</p>)}</div><button onClick={()=>navigate(()=>setEditing(editing==='facts'?null:'facts'))}>去补充</button></section>
      {editing==='facts'&&<div className="inline-editor">{['users','value','priority'].map(key=><label key={key}>{scope[key]}<textarea rows={2} value={values[key]||''} onChange={e=>edit(key,e.target.value)}/></label>)}<button disabled={locked} onClick={()=>attempt(save)}>保存补充信息</button><button onClick={()=>navigate(discard)}>取消</button></div>}
      <section className="scope-requirements"><div className="section-heading"><div><h3><Icon name="list"/>关键需求条目（已有稳定编号）</h3><p>范围选择与采纳状态分别记录；核对范围不会自动采纳候选。</p></div><button onClick={onCandidate}>＋ 新增候选需求</button></div>
      {p.items.filter(i=>i.kind==='requirement').map(i=><details className="scope-requirement" key={i.id}><summary><label onClick={e=>e.stopPropagation()}><input type="checkbox" aria-label={'本期范围 '+i.title} disabled={i.applies_to!=='to_be'} checked={ids.includes(i.id)} onChange={e=>{if(!dirty)base.current=p.revision;setIds(e.target.checked?[...ids,i.id]:ids.filter(id=>id!==i.id));setDirty(true);}}/><span className="requirement-id">{i.id}<small>v{i.content_version||1}</small></span></label><span className={'change-tag '+i.change_type}>{({new:'新增',modified:'修改',preserved:'保持',existing:'现状'} as Obj)[i.change_type]||'待核对'}</span><strong>{i.title}</strong><span className="requirement-statement">{i.statement}</span><span className="selection-tag">{({selected:'草稿已采纳',candidate:'候选未采纳',deferred:'暂缓',rejected:'未采纳'} as Obj)[i.selection_status]}</span><span>详情⌄</span></summary><div className="requirement-details"><p>{i.statement}</p><p>{({reported:'材料陈述',inferred:'推断，待核实',proposed:'建议，未成为事实'} as Obj)[i.epistemic_status]}</p><div className="toolbar"><button onClick={()=>onSource?.(i.source_refs||[])}>查看来源</button><button onClick={()=>onHelp?.({kind:'item',id:i.id,label:i.title})}>帮助澄清此项</button><label>独立采纳状态<select disabled={locked} aria-label={'采纳状态 '+i.title} value={i.selection_status} onChange={e=>onItem?.(i,e.target.value)}>{[['candidate','候选'],['selected','采纳此条'],['deferred','暂缓'],['rejected','不采纳']].map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label></div></div></details>)}
      {!p.items.some(i=>i.kind==='requirement')&&<p>尚未形成需求条目；可返回分析或补充候选，不能把空列表当作已完成。</p>}</section>
      <div className="assistant-note"><Icon name="light"/><b>核对提示</b><span>重点检查“不在本期范围”；候选采纳是独立决定。</span><button disabled={locked||!dirty} onClick={()=>attempt(save)}>保存范围草稿</button></div>
    </>}
    {phase===2&&<><details className="behavior-details"><summary>核对业务行为、验收与需求关系</summary><p>行为说明与验收来自当前条目，不会用通用规则补齐空缺。</p>{p.items.filter(i=>i.kind==='requirement'&&p.product_context?.scope_ids?.includes(i.id)).map(i=><BehaviorEditor key={i.id} item={i} mutate={mutate} busy={locked} revision={p.revision}/>)}<details><summary>本期以外的未决事项及范围决定</summary>{p.questions.filter(q=>q.status!=='answered').map(q=><QuestionScope key={q.id} question={q} mutate={mutate}/>)}</details><RequirementRelations p={p} mutate={mutate}/></details></>}
    {phase===3&&<><p>只核对功能、入口、操作、保持项与未决事项，布局细节交由 UI 设计继续完善。</p><div className="sketch-notes">{[['changes','新增或修改'],['preserved','保持不变'],['behavior','行为与待定']].map(([key,label])=><section key={key}><h3>{label}</h3><p>{values[key]||'待核对说明'}</p></section>)}<section><h3>关联需求编号</h3>{p.items.filter(i=>i.kind==='requirement'&&p.product_context?.scope_ids?.includes(i.id)).map(i=><p key={i.id}>{i.id} · v{i.content_version||1}<br/>{i.title}</p>)}</section></div><button onClick={()=>setEditing(editing?null:'sketch')}>{editing?'收起草图说明编辑':'调整草图核对说明'}</button>{editing&&<div className="inline-editor"><label className="check"><input type="checkbox" checked={values.applicable!==false} onChange={e=>edit('applicable',e.target.checked)}/>本次涉及界面或交互变化</label>{Object.entries(fields).map(([key,label])=><label key={key}>{String(label)}<textarea rows={2} value={values[key]||''} onChange={e=>edit(key,e.target.value)}/></label>)}<button disabled={locked} onClick={()=>attempt(save)}>保存草图核对说明</button></div>}</>}
    {phase===4&&<><details className="document-pair-summary"><summary>两份文档的版本与核对状态</summary><p>MRD 与 PRD 分别核对各自版本，两份有效后才能进入交接。</p><div className="document-pair">{['mrd','prd'].map(k=><div key={k}><strong>{k.toUpperCase()}</strong><p>{p.documents[k]?`文档 v${p.documents[k].document_version||'未记录'} · 底稿 v${p.documents[k].draft_revision}`:'尚未生成'}</p><p>{(p as Obj).document_review_status?.[k]?.reviewed?'当前版本已核对':'当前版本尚未核对'}</p></div>)}</div></details></>}
    {error&&<div role="alert" className="error"><p>{error} · 输入仍保留。</p>{/版本|变化/.test(error)&&<details><summary>查看已刷新内容并处理冲突</summary><p>当前底稿 v{p.revision}；编辑基于 v{base.current}。请对照下面内容，合并需要保留的修改。</p>{Object.entries(init()).filter(([,v])=>typeof v==='string').map(([k,v])=><p key={k}>{scope[k]||k}：{String(v)}</p>)}<button onClick={()=>{base.current=p.revision;setError('');}}>已核对差异，保留编辑并继续修改</button></details>}</div>}
    {phase>0&&<>{state&&!state.available&&<p className="notice">可提前查看，继续前请先完成前序核对。<button onClick={()=>go(phase===4?2:Math.max(0,phase-1))}>返回前一步</button></p>}{!!state?.missing.length&&<details className="notice"><summary>继续前还需核对 {state?.missing.length} 项</summary><ul>{state?.missing.map(x=><li key={x}>{x}</li>)}</ul></details>}<div className="step-actions"><button className="back-step" onClick={()=>go(phase===4?2:phase-1)}>← {phase===1?'返回修改输入':phase===2?'返回范围核对':phase===3?'返回规则澄清':'返回规则澄清'}</button><span>{dirty?'请先保存修改':'保存与核对均不调用模型'}</span><button className="primary" disabled={locked||!state?.available||(phase!==1&&dirty)||(!dirty&&!!state?.missing.length)} onClick={()=>attempt(async()=>{if(phase===1&&dirty)await save();else await check();})}>{['',dirty?'保存范围并重新核对':'确认范围并进入下一步','核对规则并继续','确认草图并继续','完成文档评审并进入交接'][phase]} →</button></div></>}
  </article>;
}

export function QuestionList({p,mutate,busy,onHelp}:{p:Project;mutate:Props['mutate'];busy:boolean;onHelp:(target:Obj)=>void}){
 const [answers,setAnswers]=useState<Obj>({}),[unknown,setUnknown]=useState<string[]>([]),[error,setError]=useState(''),[saving,setSaving]=useState(false);const base=useRef(p.revision);
 const dirty=Object.keys(answers).length>0;
 async function save(){const values=Object.fromEntries(Object.entries(answers).filter(([,v])=>String(v).trim()));if(Object.keys(values).length!==Object.keys(answers).length)throw Error('空白回答不会被视为已回答，请填写或选择保留未知。');await mutate('/answers',{answers:values,expected_revision:base.current});setAnswers({});}
 useDirty(p.id+'-answers',dirty,'问题回答',save,()=>setAnswers({}));
 function edit(id:string,text:string){if(!dirty)base.current=p.revision;setAnswers(v=>({...v,[id]:text}));}
 function card(q:Obj){return <article className="question-item" key={q.id}><div className="question-description"><div className="section-heading"><h3>{q.question}</h3><span className="pill">{answers[q.id]!==undefined?'已填写 · 未保存':q.status==='answered'?'已保存回答':q.blocking?'待回答 · 阻塞':'待决定'}</span></div><p className="muted">{q.why}</p><small>{q.id} · 关联：{q.affected_requirements?.map((r:Obj)=>r.id).join('、')||q.related_refs?.join('、')||'尚未关联'}</small></div><div className="question-answer"><label>你的回答<textarea rows={2} aria-label={q.question} value={answers[q.id]??q.answer??''} onChange={e=>edit(q.id,e.target.value)}/></label></div><div className="question-suggestion"><b>✦ 局部建议</b>{q.options?.length>0&&<div className="choice-list">{q.options.map((x:string)=><button key={x} onClick={()=>edit(q.id,x)}>填入建议：{x}</button>)}</div>}<div className="toolbar"><button onClick={()=>{setUnknown(v=>v.includes(q.id)?v:[...v,q.id]);setAnswers(v=>{const n={...v};delete n[q.id];return n;});}}>暂不确定，保留未知</button><button onClick={()=>onHelp({kind:'question',id:q.id,label:q.question})}>帮我分析这个问题</button></div>{unknown.includes(q.id)&&<p className="notice">仍未解决，不会自动解除阻塞；可以继续查看其他步骤。</p>}</div></article>;}
 return <article className="card questions-panel"><div className="section-heading"><h2>待澄清的问题（按需求分组）</h2><small>{p.questions.filter(q=>q.status!=='answered'&&!q.out_of_scope_reason).length} 个待答问题 · 建议不是答案</small></div>{[...p.items.filter(i=>i.kind==='requirement').map(i=>({id:i.id,label:i.id+'｜'+i.title})),{id:'unbound',label:'尚未关联具体需求'}].map(group=>{const questions=p.questions.filter(q=>q.status!=='answered'&&!q.out_of_scope_reason).filter(q=>{const actual=p.items.find(i=>i.kind==='requirement'&&((q.related_refs||[]).includes(i.id)||(q.affected_requirements||[]).some((r:Obj)=>r.id===i.id)));return (actual?.id||'unbound')===group.id;});return questions.length?<section className="question-group" key={group.id}><h3>{group.label}<small>{questions.length} 项待决定</small></h3>{questions.map(card)}</section>:null;})}{!p.questions.length&&<p>尚无澄清问题。可先核对资料理解与本期范围。</p>}<details className="answered-editor"><summary>已回答 · {p.questions.filter(q=>q.status==='answered').length}（可修改）</summary>{p.questions.filter(q=>q.status==='answered').map(card)}</details>{error&&<p role="alert" className="error">{error}</p>}<button className="primary" disabled={!dirty||busy||saving} onClick={async()=>{setSaving(true);try{await save();setError('');}catch(e){setError((e as Error).message);}finally{setSaving(false);}}}>保存本次回答</button><div className="question-results"><section><h3><Icon name="check"/>已保存回答 <small>{p.questions.filter(q=>q.status==='answered').length} 项</small></h3>{p.questions.filter(q=>q.status==='answered').map(q=><p key={q.id}><b>{q.question}</b><br/>{q.answer}</p>)}{!p.questions.some(q=>q.status==='answered')&&<p>尚无已保存回答。未保存输入和建议不会列入此处。</p>}</section><section><h3><Icon name="question"/>仍待决定 <small>{p.questions.filter(q=>q.status!=='answered').length} 项</small></h3>{p.questions.filter(q=>q.status!=='answered').map(q=><p key={q.id}>{q.question}<small>{q.out_of_scope_reason?'本期以外，仍未知':q.blocking?'本期阻塞项':'待决定'}</small></p>)}</section></div></article>;
}

function RequirementRelations({p,mutate}:{p:Project;mutate:Props['mutate']}){
  const [source,setSource]=useState(''),[target,setTarget]=useState(''),[relation,setRelation]=useState('refines'),[error,setError]=useState('');
  const reqs=p.items.filter(i=>i.kind==='requirement');
  return <details><summary>需求的父子、细化与依赖关系</summary><p>拆分或取代时保留原编号，各子需求有自己的编号。关系不代表实现或测试通过。</p>{(p.requirement_relations||[]).map((r:Obj,n:number)=><p key={n}>{r.source.id} v{r.source.version} → {r.type} → {r.target.id} v{r.target.version}</p>)}{reqs.length>1&&<><label>起始需求<select value={source} onChange={e=>setSource(e.target.value)}><option value="">选择需求</option>{reqs.map(i=><option key={i.id} value={i.id}>{i.id}｜{i.title}</option>)}</select></label><label>关系<select value={relation} onChange={e=>setRelation(e.target.value)}>{[['parent_of','是其父需求'],['refines','细化'],['replaces','取代'],['depends_on','依赖']].map(([k,n])=><option key={k} value={k}>{n}</option>)}</select></label><label>目标需求<select value={target} onChange={e=>setTarget(e.target.value)}><option value="">选择需求</option>{reqs.map(i=><option key={i.id} value={i.id}>{i.id}｜{i.title}</option>)}</select></label><button disabled={!source||!target||source===target} onClick={async()=>{try{await mutate('/requirement-relations',{source_id:source,target_id:target,relation});setError('');}catch(e){setError((e as Error).message);}}}>记录关系</button></>}{error&&<p role="alert">{error}</p>}<p><a href={'/api/projects/'+p.id+'/requirements-exchange'} download={p.name+'-需求交换.json'}>导出结构化需求与关系</a>（当前草稿；正式交接使用确认基线）</p></details>;
}

function BehaviorEditor({item,mutate,busy,revision}:{item:Obj;mutate:Props['mutate'];busy:boolean;revision:number}){
  const [values,setValues]=useState<Obj>(item.behavior||{}),[kind,setKind]=useState(item.change_type||'modified'),[dirty,setDirty]=useState(false),[error,setError]=useState('');
  useEffect(()=>{if(!dirty){setValues(item.behavior||{});setKind(item.change_type||'modified');}},[item,dirty]);
  const base=useRef(revision); useEffect(()=>{if(!dirty)base.current=revision;},[revision,dirty]);
  const save=async()=>{await mutate('/items/'+item.id+'/behavior',{values,change_type:kind,expected_revision:base.current});setDirty(false);setError('');};
  useDirty(item.id+'-behavior',dirty,'需求行为 '+item.title,save,()=>{setValues(item.behavior||{});setDirty(false);});
  return <details><summary>{item.id}｜{item.title} · v{item.content_version||1}{dirty?' · 未保存':''}</summary><p>{item.statement}</p><label>本次性质<select value={kind} onChange={e=>{setKind(e.target.value);setDirty(true);}}>{[['new','新增'],['modified','修改'],['preserved','保持约束'],['existing','现状']].map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label>{Object.entries(behavior).map(([key,label])=><label key={key}>{String(label)}<textarea value={values[key]||''} onChange={e=>{setValues(v=>({...v,[key]:e.target.value}));setDirty(true);}}/></label>)}{error&&<p role="alert">{error}</p>}<button disabled={busy||!dirty} onClick={async()=>{try{await save();}catch(e){setError((e as Error).message);}}}>保存此需求行为</button></details>;
}
function QuestionScope({question:q,mutate}:{question:Obj;mutate:Props['mutate']}){
  const [reason,setReason]=useState(q.out_of_scope_reason||''),[error,setError]=useState('');
  return <details><summary>{q.question}{q.out_of_scope_reason?' · 已移出本期，仍未知':''}</summary><p>影响需求：{q.affected_requirements?.map((r:Obj)=>r.id).join('、')||q.related_refs?.join('、')||'尚待关联范围'}</p><p>{q.why} · 影响第{q.blocking_stage||3}步</p><label>明确移出本期的理由（清空可恢复）<textarea value={reason} onChange={e=>setReason(e.target.value)}/></label><p>不改变原问题、答案或条目采纳状态；本期仍依赖的规则不得移出。</p><button onClick={async()=>{try{await mutate('/questions/'+q.id+'/scope',{out_of_scope_reason:reason});}catch(e){setError((e as Error).message);}}}>保存范围决定</button>{error&&<p role="alert">{error}</p>}</details>;
}
