import React, { useState } from 'react';
import { useDialog } from './shell';

type Obj = Record<string, any>;
const stages: Record<string, string> = { ingest: '理解材料', brainstorm: '探索方案', clarify: '澄清规则', change: '修改方案', ui: '生成页面原型', prd: '生成需求文档', review: '审查当前版本', vision: '理解图片' };
const kinds: Record<string, string> = { goal: '本期目标', actor: '目标用户', requirement: '需求', rule: '规则', acceptance: '验收条件', non_goal: '暂不包含', constraint: '保持不变' };
const status: Record<string, string> = { candidate: '候选', selected: '本期已选', deferred: '暂缓', rejected: '未采纳', open: '待回答', answered: '已回答' };

export function DecisionCard({ question, submit }: { question: Obj, submit: (answer: string) => void }) {
  const [answer, setAnswer] = useState(question.answer || ''), [unknown, setUnknown] = useState(false);
  return <article className="card decision-card"><div className="eyebrow">{question.blocking ? '关键决定' : '可后续决定'} · {status[question.status] || question.status}</div><h3>{question.question}</h3><p className="muted">{question.why}</p>
    {question.status === 'answered' ? <details><summary>已回答：{question.answer} · 展开修改</summary><textarea aria-label={question.question} value={answer} onChange={e => setAnswer(e.target.value)} /><button onClick={() => submit(answer)} disabled={!answer.trim()}>更新回答</button></details> : <>
      <div className="choice-list">{question.options.map((option: string) => <button key={option} onClick={() => { setAnswer(option); setUnknown(false); }}>{option}</button>)}</div>
      <textarea aria-label={question.question} value={answer} onChange={e => setAnswer(e.target.value)} placeholder="输入你的决定或补充约束" />
      <div className="toolbar"><button onClick={() => setUnknown(true)}>暂时不知道，先看方案</button><button className="primary" disabled={!answer.trim()} onClick={() => submit(answer)}>保存回答</button></div>
      {unknown && <p className="notice">问题仍待回答；可先探索方案，不会将它视为已解决。</p>}
    </>}
  </article>;
}

export function ConversationPanel({ project, message, setMessage, stage, setStage, docType, setDocType, onRun, runActive, busy, onAnswer, showAdvanced, setShowAdvanced, showAllQuestions, setShowAllQuestions }: { project: Obj; message: string; setMessage: (s: string) => void; stage: string; setStage: (s: string) => void; docType: string; setDocType: (s: string) => void; onRun: () => void; runActive: boolean; busy: boolean; onAnswer: (id: string, answer: string) => void; showAdvanced: boolean; setShowAdvanced: (v: boolean) => void; showAllQuestions: boolean; setShowAllQuestions: (v: boolean) => void }) {
  const open = project.questions.filter((q: Obj) => q.status !== 'answered'), answered = project.questions.filter((q: Obj) => q.status === 'answered');
  return <section className="conversation-panel"><div className="conversation-scroll"><div className="section-heading"><div><p className="eyebrow">讨论工作台</p><h2>把关键问题说清楚</h2></div><span>建议不会自动成为已确认需求</span></div>
    {!project.messages.length && <div className="empty"><h3>从目标或材料开始</h3><p>描述现状、本期想改变的事，以及不能变的约束。材料发送前仍需确认接收端和范围。</p></div>}
    <div className="messages">{project.messages.map((m: Obj, index: number) => <article key={index} className={'message ' + m.role}><small>{m.role === 'user' ? '你' : stages[m.stage] || '需求助手'}</small><p>{m.text}</p>{m.response?.limitations?.length > 0 && <div className="notice">{m.response.limitations.join('；')}</div>}{m.response?.findings?.map((f: Obj, j: number) => <p key={j} className={f.severity === 'blocker' ? 'error' : 'notice'}>{f.message} · {f.suggested_resolution}</p>)}</article>)}</div>
    {open.length > 0 && <><h3>待你决定 · {open.length}</h3>{open.slice(0, showAllQuestions ? undefined : 2).map((q: Obj) => <DecisionCard key={q.id} question={q} submit={answer => onAnswer(q.id, answer)} />)}</>}
    {open.length > 2 && <button onClick={() => setShowAllQuestions(!showAllQuestions)}>{showAllQuestions ? '收起其余问题' : '展开其余 ' + (open.length - 2) + ' 个问题'}</button>}
    {answered.length > 0 && <details><summary>已回答的问题 · {answered.length}（可修改）</summary>{answered.map((q: Obj) => <DecisionCard key={q.id} question={q} submit={answer => onAnswer(q.id, answer)} />)}</details>}
  </div><div className="composer"><label className="visually-hidden" htmlFor="discussion-input">本轮想讨论的内容</label><textarea id="discussion-input" aria-label="本轮想讨论的内容" value={message} disabled={busy} onChange={e => setMessage(e.target.value)} onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey && !e.nativeEvent.isComposing) { e.preventDefault(); if (!busy && !runActive) onRun(); } }} placeholder="描述目标、补充决定，或要求比较方案……" />
      <div className="quick-actions">{[['clarify', '继续讨论'], ['brainstorm', '探索方案'], ['clarify', '澄清规则'], ['change', '修改方案']].map(([value, label]) => <button key={label} className={stage === value ? 'selected' : ''} onClick={() => setStage(value)}>{label}</button>)}</div>
      <div className="toolbar"><span className="muted">本次用途：{stages[stage]}</span><button onClick={() => setShowAdvanced(!showAdvanced)}>调整用途</button><button className="primary" disabled={busy || runActive} onClick={onRun}>发送并运行</button></div>
      {showAdvanced && <div className="advanced-stage"><label>分析阶段<select aria-label="分析阶段" value={stage} onChange={e => setStage(e.target.value)}>{Object.entries(stages).map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></label>{stage === 'prd' && <label>文档类型<select aria-label="生成文档类型" value={docType} onChange={e => setDocType(e.target.value)}><option value="prd">PRD</option><option value="mrd">MRD</option></select></label>}<small>发送将触发一次模型任务，可能计费。结果仍须人工核对。</small></div>}
    </div></section>;
}

export function ArtifactTabs({ project, tab, setTab, onOption, onItem, onEditItem, onStage, onActivate, onReject, onNavigate, previewUrl, runs, models, onCancel, onResume }: { project: Obj; tab: string; setTab: (s: string) => void; onOption: (option: Obj, status: string) => void; onItem: (item: Obj, status: string) => void; onEditItem: (item: Obj, statement: string) => void; onStage: (s: string) => void; onActivate: (id: string) => void; onReject: (id: string) => void; onNavigate: (tab: string) => void; previewUrl: string; runs: Obj[]; models: Obj; onCancel: (id: string) => void; onResume: (id: string) => void }) {
  const [editing, setEditing] = useState<Obj | null>(null), [editText, setEditText] = useState('');
  useDialog(Boolean(editing), () => setEditing(null));
  const selected = project.items.filter((i: Obj) => i.selection_status === 'selected');
  const groups = ['actor', 'goal', 'constraint', 'non_goal', 'requirement', 'rule', 'acceptance'];
  return <section className="artifact-panel"><div className="artifact-tabs" role="tablist" aria-label="工作成果">{[['summary', '需求摘要'], ['options', '方案对比'], ['prototype', '页面原型'], ['document', 'PRD 草稿']].map(([id, label]) => <button role="tab" aria-selected={tab === id} key={id} className={tab === id ? 'active' : ''} onClick={() => setTab(id)}>{label}</button>)}</div>
    <div className="artifact-scroll">
      {tab === 'summary' && <><div className="section-heading"><h2>需求摘要</h2><span>草稿 v{project.revision}</span></div>{!project.items.length && <div className="empty">底稿尚无条目。先添加材料并运行理解阶段。</div>}{groups.map(kind => { const items = selected.filter((i: Obj) => i.kind === kind); return items.length > 0 && <article className="card" key={kind}><h3>{kinds[kind]}</h3>{items.map((i: Obj) => <div key={i.id} className="summary-item"><strong>{i.title}</strong><p>{i.statement}</p><small>{i.id} · 来源 {i.source_refs?.map((s: Obj) => s.excerpt_id).join('、') || '待核对'}</small><div><button onClick={() => onNavigate('sources')}>查看来源</button><button onClick={() => { setEditing(i); setEditText(i.statement); }}>编辑原文</button></div></div>)}</article>; })}{project.items.filter((i: Obj) => i.selection_status === 'candidate').length > 0 && <article className="card"><h3>待采纳候选</h3>{project.items.filter((i: Obj) => i.selection_status === 'candidate').map((i: Obj) => <div key={i.id} className="summary-item"><strong>{i.title}</strong><p>{i.statement}</p><div className="toolbar"><button onClick={() => onItem(i, 'selected')}>采纳</button><button onClick={() => onItem(i, 'deferred')}>暂缓</button></div></div>)}</article>}<details><summary>查看全部底稿条目与状态</summary>{project.items.map((i: Obj) => <div key={i.id} className="summary-item"><strong>{i.id} · {i.title} · {status[i.selection_status]}</strong><p>{i.statement}</p><select aria-label={'采纳状态 ' + i.title} value={i.selection_status} onChange={e => onItem(i, e.target.value)}>{['candidate', 'selected', 'deferred', 'rejected'].map(value => <option key={value} value={value}>{status[value]}</option>)}</select><button onClick={() => { setEditing(i); setEditText(i.statement); }}>编辑原文</button></div>)}</details></>}
      {tab === 'options' && <><div className="section-heading"><h2>方案对比</h2><button onClick={() => onStage('brainstorm')}>探索方案</button></div>{!project.options.length && <div className="empty">尚无方案。数量由分析结果决定。</div>}{project.options.map((o: Obj) => <article className="card" key={o.id}><div className="section-heading"><h3>{o.name}</h3><span className="pill">{status[o.selection_status]}</span></div><p><strong>用户路径</strong><br />{o.user_path}</p>{[['benefits', '收益'], ['costs', '代价'], ['risks', '风险'], ['mvp_scope', '最小范围'], ['open_questions', '待定事项']].map(([key, label]) => <p key={key}><strong>{label}：</strong>{o[key]?.join('；') || '未列出'}</p>)}<small>关联条目：{o.proposed_item_refs?.join('、') || '无'}</small><div className="toolbar"><button onClick={() => setTab('prototype')}>预览</button><button onClick={() => onOption(o, 'selected')}>采纳</button><button onClick={() => onOption(o, 'deferred')}>暂缓</button></div></article>)}</>}
      {tab === 'prototype' && <PrototypeCanvas project={project} url={previewUrl} onStage={onStage} onActivate={onActivate} onReject={onReject} />}
      {tab === 'document' && <><div className="section-heading"><h2>PRD 草稿</h2><button onClick={() => onStage('prd')}>生成或重新生成</button></div>{project.documents.prd ? <DocumentViewer document={project.documents.prd} items={project.items} currentRevision={project.revision} currentBriefHash={project.hashes.brief_hash} updateNeeded={project.stale_document_kinds?.includes('prd')} downloadRoot={previewUrl.replace('/prototype', '')} /> : <div className="empty">尚未生成 PRD。生成是明确的模型任务。</div>}</>}
      <details className="task-details"><summary>任务详情与接收端</summary><p>主分析接收端：{models.model?.name} · {models.model?.base_url} · Key {models.model?.key_configured ? '已配置' : '未配置'}</p>{runs.slice(-5).reverse().map((r: Obj) => <div key={r.id} className="card"><strong>{stages[r.stage]} · {r.status}</strong><p>{r.error ? r.message : `调用 ${r.calls} 次 · 费用 ${r.cost ?? '未知'}`}</p>{['queued', 'running'].includes(r.status) ? <button onClick={() => onCancel(r.id)}>取消后续请求</button> : ['failed', 'paused_budget', 'cancelled'].includes(r.status) && <button onClick={() => onResume(r.id)}>继续此阶段（可能计费）</button>}</div>)}</details>
    </div>{editing && <div className="modal-backdrop"><form className="modal" onSubmit={e => { e.preventDefault(); onEditItem(editing, editText); setEditing(null); }}><h2>编辑需求原文</h2><p>保存后形成新草稿，旧基线保持不变。</p><textarea aria-label="需求原文" value={editText} onChange={e => setEditText(e.target.value)} required /><div className="toolbar"><button type="button" onClick={() => setEditing(null)}>取消</button><button className="primary">保存原文</button></div></form></div>}</section>;
}

export function PrototypeCanvas({ project, url, onStage, onActivate, onReject }: { project: Obj; url: string; onStage: (s: string) => void; onActivate?: (id: string) => void; onReject?: (id: string) => void }) {
  const [expanded, setExpanded] = useState(false);
  return <div className={expanded ? 'prototype-canvas expanded' : 'prototype-canvas'}><div className="section-heading"><div><h2>业务原型画布</h2><small>低保真交互 · 模拟数据 · 不连接业务系统</small></div><div className="toolbar"><button onClick={() => setExpanded(!expanded)}>{expanded ? '收起画布' : '展开画布'}</button><button onClick={() => onStage('ui')}>生成页面候选</button></div></div>
    {project.ui ? <><p className="notice">UI v{project.ui.spec.draft_revision} · 对应底稿 v{project.ui.verification?.draft_revision || project.ui.spec.draft_revision}{project.document_update_needed ? ' · 文档及审查需要更新' : ''}</p><iframe key={project.hashes.ui_spec_hash} title="低保真页面预览" sandbox="allow-scripts" src={url + '?content=' + project.hashes.ui_spec_hash} className="prototype" /><details><summary>设计意图与关联</summary><p>{project.ui.spec.design_intent}</p>{project.ui.spec.pages.map((page: Obj) => <p key={page.page_id}>{page.title}：{page.requirement_refs.join('、')}</p>)}</details>
      {(project.ui_candidates || []).filter((c: Obj) => c.status === 'candidate').map((candidate: Obj) => <article className="card" key={candidate.id}><h3>待比较的页面候选</h3><p>原设计意图：{project.ui.spec.design_intent}</p><p>候选设计意图：{candidate.spec.design_intent}</p><p>页面布局差异：{candidate.spec.pages.map((page: Obj) => page.title + '（' + page.regions.map((region: Obj) => region.components.map((component: Obj) => component.type + ' ' + component.label).join('、')).join('；') + '）').join('；')}</p><p className="notice">保持不变：当前底稿中的本期规则与验收条目。候选激活不会修改这些条目；若规则需变更，请返回需求澄清。</p><iframe title="候选页面预览" sandbox="allow-scripts" src={url.replace('/prototype', '/ui-candidates/' + candidate.id + '/prototype')} className="prototype" /><div className="toolbar"><button onClick={() => onReject?.(candidate.id)}>保留旧方案</button><button className="primary" onClick={() => onActivate?.(candidate.id)}>采纳候选并建立新草稿</button></div></article>)}
    </> : <div className="empty">尚未生成业务页面。画布不使用固定业务示例。</div>}
  </div>;
}

export function DocumentViewer({ document, items, currentRevision, currentBriefHash, updateNeeded = false, historical = false, downloadRoot }: { document: Obj; items: Obj[]; currentRevision: number; currentBriefHash: string; updateNeeded?: boolean; historical?: boolean; downloadRoot: string }) {
  const [selected, setSelected] = useState(document.content.sections[0]?.section_id);
  const stale = document.draft_revision !== currentRevision || document.brief_hash !== currentBriefHash || updateNeeded;
  const snapshot: Obj[] = document.item_snapshot || (stale || historical ? [] : items);
  return <><p className={stale || historical ? 'notice' : 'muted'}>{historical ? '历史文档只读 · ' : stale ? '基于旧版本 · ' : ''}底稿 v{document.draft_revision} · {document.content.title}</p><div className="document-layout"><nav aria-label="文档目录">{document.content.sections.map((section: Obj) => <button key={section.section_id} className={selected === section.section_id ? 'active' : ''} onClick={() => { setSelected(section.section_id); globalThis.document.getElementById(section.section_id)?.scrollIntoView(); }}>{section.title}</button>)}</nav><div className="document-reader"><h2>{document.content.title}</h2>{document.content.sections.map((section: Obj) => <section key={section.section_id} id={section.section_id} className="document-section"><h3>{section.title}</h3>{section.blocks.map((block: Obj, index: number) => <p key={index}>{block.text || block.ref_ids.map((id: string) => { const source = snapshot.find((i: Obj) => i.id === id); return source ? `${id} — ${source.statement}` : `${id} — 旧版原文不可用`; }).join('\n')}</p>)}</section>)}</div></div>{!stale && !historical && <div className="toolbar">{['docx', 'md', 'zip'].map(format => <a key={format} href={downloadRoot + '/documents/' + document.content.document_type + '/' + format} download>{format.toUpperCase()} 下载</a>)}</div>}
  </>;
}
